package com.urkaz.sons_of_macabre;

import com.curseforge.macabre.init.MacabreModItems;
import com.mojang.logging.LogUtils;
import com.urkaz.sons_of_macabre.config.Config;
import com.urkaz.sons_of_macabre.config.ConfigCondition;
import net.kyrptonaught.customportalapi.api.CustomPortalBuilder;
import net.mcreator.sonsofsins.init.SonsOfSinsModBlocks;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.material.MapColor;
import net.minecraftforge.common.crafting.CraftingHelper;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.config.ModConfig;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.slf4j.Logger;

import java.util.HashMap;

@Mod(SonsOfMacabre.MODID)
public class SonsOfMacabre {

    public static final String MODID = "sons_of_macabre";
    public static final Logger LOGGER = LogUtils.getLogger();
    public static final HashMap<String, MapColor> MACABRE_BLOCK_MAP_COLORS = new HashMap<>() {{
        put("HardStoneBlock", MapColor.DEEPSLATE);
        put("DampDirtBlock", MapColor.COLOR_BROWN);
        put("BrittlestoneBlock", MapColor.DEEPSLATE);
        put("LivingDirtBlock", MapColor.NETHER);
        put("BreatherBlock", MapColor.NETHER);
        put("ClosedBreatherBlock", MapColor.NETHER);
        put("EmptyWatcherBlock", MapColor.NETHER);
        put("WatcherBlock", MapColor.NETHER);
        put("HemoCapBlock", MapColor.NETHER);
        put("FungusStemBlock", MapColor.SAND);
        put("GoreSandBlock", MapColor.DIRT);
        put("SoakedStoneBlock", MapColor.DIRT);
        put("SoakedWoodBlock", MapColor.DEEPSLATE);
        put("SoakedLogBlock", MapColor.WARPED_HYPHAE);
        put("SoakedPlanksBlock", MapColor.WARPED_HYPHAE);
        put("SoakedSlabBlock", MapColor.WARPED_HYPHAE);
        put("SoakedStairsBlock", MapColor.WARPED_HYPHAE);
        put("CrawlingDirtBlock", MapColor.QUARTZ);
        put("CrawlingLivingDirtBlock", MapColor.TERRACOTTA_MAGENTA);
        put("GoreQuicksandBlock", MapColor.DIRT);
        put("SkinBlock", MapColor.QUARTZ);
        put("LumpyDirtBlock", MapColor.CRIMSON_HYPHAE);
        put("CrumblingDirtBlock", MapColor.TERRACOTTA_ORANGE);
        put("DrDirtBlock", MapColor.TERRACOTTA_LIGHT_GRAY);
        put("WeakStoneBlock", MapColor.DEEPSLATE);
        put("NumbDirtBlock", MapColor.DEEPSLATE);
        put("TumorDirtBlock", MapColor.TERRACOTTA_WHITE);
        put("CompressedFleshBlock", MapColor.NETHER);
        put("FleshSlabBlock", MapColor.NETHER);
        put("FleshStairsBlock", MapColor.NETHER);
        put("ToxicDirtBlock", MapColor.TERRACOTTA_WHITE);
        put("VeinsBlock", MapColor.TERRACOTTA_RED);
        put("RottingDirtBlock", MapColor.NETHER);
        put("HardBrickBlock", MapColor.DEEPSLATE);
        put("BloodClotOreBlock", MapColor.CRIMSON_HYPHAE);
        put("BloodClotBlockBlock", MapColor.NETHER);
        put("MeatWallBlock", MapColor.TERRACOTTA_PINK);
        put("CrackingBoneBlock", MapColor.TERRACOTTA_LIGHT_GRAY);
        put("HardMeatWallBlock", MapColor.TERRACOTTA_PINK);
        put("DamagedTissueBlock", MapColor.WARPED_HYPHAE);
        put("DamageVeinsBlock", MapColor.WARPED_HYPHAE);
        put("DamagedSkinBlock", MapColor.WARPED_HYPHAE);
        put("NecrosisSkinBlock", MapColor.CRIMSON_HYPHAE);
        put("NecrosisFleshBlock", MapColor.CRIMSON_HYPHAE);
        put("NecrosisMuscleBlock", MapColor.WARPED_HYPHAE);
        put("NecrosisVeinsBlock", MapColor.WARPED_HYPHAE);
        put("ToughPlasmaBlock", MapColor.TERRACOTTA_YELLOW);
        put("FatBlockBlock", MapColor.TERRACOTTA_YELLOW);
        put("FatOreBlock", MapColor.TERRACOTTA_YELLOW);
        put("PlasmaOreBlock", MapColor.TERRACOTTA_YELLOW);
        put("FerrumOreBlock", MapColor.DEEPSLATE);
        put("FerrumBlockBlock", MapColor.METAL);
        put("AbhorrentBlockBlock", MapColor.GOLD);
        put("BrittlestoneSlabBlock", MapColor.DEEPSLATE);
        put("BrittlestoneStairsBlock", MapColor.DEEPSLATE);
        put("BrittlestoneWallsBlock", MapColor.DEEPSLATE);
        put("HardBrickPillarBlock", MapColor.DEEPSLATE);
        put("HardBrickSlabBlock", MapColor.DEEPSLATE);
        put("HardBrickStairsBlock", MapColor.DEEPSLATE);
        put("HardBrickWallsBlock", MapColor.DEEPSLATE);
        put("SoftBrickBlock", MapColor.DEEPSLATE);
        put("LongBrickBlock", MapColor.DEEPSLATE);
        put("SoftBrickSlabBlock", MapColor.DEEPSLATE);
        put("SoftBrickStairsBlock", MapColor.DEEPSLATE);
        put("SoftBrickWallsBlock", MapColor.DEEPSLATE);
        put("LongBrickSlabBlock", MapColor.DEEPSLATE);
        put("LongBrickStairsBlock", MapColor.DEEPSLATE);
        put("LongBrickWallsBlock", MapColor.DEEPSLATE);
        put("RottenBlockBlock", MapColor.COLOR_GREEN);
        put("AcidPoolBlock", MapColor.COLOR_LIGHT_GREEN);
        put("GumsBlock", MapColor.TERRACOTTA_PINK);
        put("GumBlockBlock", MapColor.TERRACOTTA_PINK);
        put("TeethingWoodBlock", MapColor.QUARTZ);
        put("TeethingLogBlock", MapColor.COLOR_MAGENTA);
        put("TeethingRootsBlock", MapColor.QUARTZ);
        put("TeethingPlanksBlock", MapColor.COLOR_MAGENTA);
        put("TeethingSlabBlock", MapColor.COLOR_MAGENTA);
        put("TeethingStairsBlock", MapColor.COLOR_MAGENTA);
        put("TeethingPressurePlateBlock", MapColor.COLOR_MAGENTA);
        put("TeethingButtonBlock", MapColor.NONE);
        put("DungeonWallsBoneBlock", MapColor.SAND);
        put("DungeonWallsTeethBlock", MapColor.QUARTZ);
        put("SolidRockBlock", MapColor.DEEPSLATE);
        put("MortemDirtBlock", MapColor.COLOR_CYAN);
        put("SlitBlock", MapColor.CRIMSON_STEM);
        put("SlitOffBlock", MapColor.COLOR_CYAN);
        put("GeyserBlock", MapColor.CRIMSON_STEM);
        put("GeyserOffBlock", MapColor.COLOR_CYAN);
        put("ChainBlock", MapColor.METAL);
        put("IntestineWallBlock", MapColor.SAND);
        put("DrenchedPlanksBlock", MapColor.FIRE);
        put("DrenchedSlabsBlock", MapColor.FIRE);
        put("DrenchedStairsBlock", MapColor.FIRE);
        put("DrenchedTrapdoorBlock", MapColor.FIRE);
        put("DrenchedPressurePlateBlock", MapColor.FIRE);
        put("DrenchedButtonBlock", MapColor.NONE);
        put("MoldedStoneBlock", MapColor.COLOR_CYAN);
        put("MoldCapBlock", MapColor.COLOR_CYAN);
        put("MoltedStoneBlock", MapColor.TERRACOTTA_YELLOW);
        put("WastedGrassBlock", MapColor.TERRACOTTA_PURPLE);
        put("WastedWoodBlock", MapColor.TERRACOTTA_PURPLE);
        put("WastedLogBlock", MapColor.TERRACOTTA_PURPLE);
        put("WastedPlanksBlock", MapColor.TERRACOTTA_PURPLE);
        put("WastedStairsBlock", MapColor.TERRACOTTA_PURPLE);
        put("WastedSlabBlock", MapColor.TERRACOTTA_PURPLE);
        put("PetrifiedRockBlock", MapColor.TERRACOTTA_LIGHT_GRAY);
        put("CrackedLongBrickBlock", MapColor.DEEPSLATE);
        put("BloodiedLongBrickBlock", MapColor.WARPED_HYPHAE);
        put("DecomposedBricksBlock", MapColor.DEEPSLATE);
        put("LifelessSandBlock", MapColor.SAND);
        put("SlimThornBlock", MapColor.NETHER);
        put("DriedWoodBlock", MapColor.COLOR_BROWN);
        put("DriedLogBlock", MapColor.TERRACOTTA_YELLOW);
        put("DriedPlanksBlock", MapColor.TERRACOTTA_YELLOW);
        put("DriedStairsBlock", MapColor.TERRACOTTA_YELLOW);
        put("DriedSlabBlock", MapColor.TERRACOTTA_YELLOW);
        put("DeadLogBlock", MapColor.COLOR_BLACK);
        put("MediumDeadLogBlock", MapColor.COLOR_BLACK);
        put("SlimDeadLogBlock", MapColor.COLOR_BLACK);
        put("BaalTrophyBlock", MapColor.FIRE);
        put("GargamawTrophyBlock", MapColor.FIRE);
        put("GomoriaTrophyBlock", MapColor.FIRE);
        put("ValamonTrophyBlock", MapColor.FIRE);
        put("MorphegorTrophyBlock", MapColor.FIRE);
        put("HemoCapEdgeBlock", MapColor.NETHER);
        put("DriedButtonBlock", MapColor.NONE);
        put("WastedButtonBlock", MapColor.NONE);
        put("SoakedButtonBlock", MapColor.NONE);
        put("TeethingLeavesBlock", MapColor.CRIMSON_HYPHAE);
        put("ScorchingTorchBlock", MapColor.TERRACOTTA_YELLOW);
        put("RibsLadderBlock", MapColor.NONE);
        put("ToxicMossBlock", MapColor.COLOR_LIGHT_GREEN);
        put("CreepingTumorBlock", MapColor.TERRACOTTA_WHITE);
        put("GloombloomseedlingBlock", MapColor.NONE);
        put("BloodStringsBlock", MapColor.NETHER);
        put("BloodStringsOozingBlock", MapColor.TERRACOTTA_YELLOW);
        put("BloodStringsShortBlock", MapColor.NETHER);
        put("BloodStringsTallBlock", MapColor.NETHER);
        put("FingersBlock", MapColor.NETHER);
        put("EyeflowerBlock", MapColor.NONE);
        put("EyeveinBlock", MapColor.NONE);
        put("EmptyEyeveinBlock", MapColor.NONE);
        put("ToxicFlowerBlock", MapColor.COLOR_LIGHT_GREEN);
        put("ToxicWeedBlock", MapColor.COLOR_LIGHT_GREEN);
        put("GumsLayer2Block", MapColor.TERRACOTTA_PINK);
        put("GumsLayer3Block", MapColor.TERRACOTTA_PINK);
        put("GumsLayerBlock", MapColor.TERRACOTTA_PINK);
        put("PimplesBlock", MapColor.QUARTZ);
        put("PoppedPimplesBlock", MapColor.QUARTZ);
        put("HairsBlock", MapColor.QUARTZ);
        put("BlackheadsBlock", MapColor.COLOR_BLACK);
        put("CreepingSkinBlock", MapColor.TERRACOTTA_WHITE);
        put("PulledSkinBlock", MapColor.TERRACOTTA_WHITE);
        put("BloodyFlowerBlock", MapColor.NETHER);
        put("BigTumorDownBlock", MapColor.TERRACOTTA_PURPLE);
        put("BigTumorMiddleBlock", MapColor.TERRACOTTA_WHITE);
        put("BigTumorTopBlock", MapColor.TERRACOTTA_PURPLE);
        put("LooseSkin2Block", MapColor.NONE);
        put("LoseSkinBlock", MapColor.NONE);
        put("GumbrushBlock", MapColor.TERRACOTTA_PINK);
        put("BigtoothBlock", MapColor.NONE);
        put("VeinBlock", MapColor.NETHER);
        put("BloodweedBlock", MapColor.NETHER);
        put("MortemStringsBlock", MapColor.COLOR_CYAN);
        put("PostMortemStringsBlock", MapColor.CRIMSON_STEM);
        put("MortemHairsBlock", MapColor.COLOR_CYAN);
        put("PostMortemHairsBlock", MapColor.CRIMSON_STEM);
        put("IllDirtBlock", MapColor.COLOR_CYAN);
        put("DunTeethBlock", MapColor.QUARTZ);
        put("DunToothBlock", MapColor.QUARTZ);
        put("GlowingPimpleBlock", MapColor.QUARTZ);
        put("Ba1Block", MapColor.NETHER);
        put("Ba2Block", MapColor.NETHER);
        put("Ba3Block", MapColor.TERRACOTTA_YELLOW);
        put("Ba4Block", MapColor.TERRACOTTA_YELLOW);
        put("Bubbles2Block", MapColor.NONE);
        put("Bubbles3Block", MapColor.NONE);
        put("BubblesBlock", MapColor.NONE);
        put("HeartFruitBlock", MapColor.TERRACOTTA_PURPLE);
        put("TumorBlock", MapColor.TERRACOTTA_PURPLE);
        put("SandLayer2Block", MapColor.DIRT);
        put("SandLayer3Block", MapColor.DIRT);
        put("SandLayerBlock", MapColor.DIRT);
        put("Bone1Block", MapColor.NONE);
        put("Bone2Block", MapColor.NONE);
        put("Bone3Block", MapColor.NONE);
        put("RibcageBlock", MapColor.TERRACOTTA_WHITE);
        put("Skull1Block", MapColor.TERRACOTTA_WHITE);
        put("Skull2Block", MapColor.TERRACOTTA_WHITE);
        put("DeadflowerBlock", MapColor.STONE);
        put("ThornBlock", MapColor.NETHER);
        put("ThornTopBlock", MapColor.NETHER);
        put("SmallThornBlock", MapColor.NETHER);
        put("LooseBorrowBlock", MapColor.NETHER);
        put("BorrowBlock", MapColor.NETHER);
        put("GoreUndersandBlock", MapColor.DIRT);
        put("BoneSpikesBlock", MapColor.QUARTZ);
        put("BoneSpikesSharpBlock", MapColor.QUARTZ);
        put("GraveBarBlock", MapColor.NONE);
        put("CemeteryBrickBlock", MapColor.STONE);
        put("CemeteryStairsBlock", MapColor.STONE);
        put("CemeteryWallBlock", MapColor.STONE);
        put("Grave2Block", MapColor.STONE);
        put("Grave3Block", MapColor.STONE);
        put("Grave4Block", MapColor.STONE);
        put("GraveBlock", MapColor.STONE);
        put("GravestonePlateBlock", MapColor.STONE);
        put("RuinLootBlock", MapColor.COLOR_BLACK);
        put("BetterRuinLootBlock", MapColor.COLOR_BLACK);
        put("BloodypadBlock", MapColor.NETHER);
        put("DeadbushBlock", MapColor.STONE);
        put("MoldFungusBlock", MapColor.SAND);
        put("StalactiteBlock", MapColor.DEEPSLATE);
        put("StalagmiteBlock", MapColor.DEEPSLATE);
        put("SmallrockpileBlock", MapColor.DEEPSLATE);
        put("RockpileBlock", MapColor.DEEPSLATE);
        put("SmallflowerBlock", MapColor.NONE);
        put("HemobannerBlock", MapColor.FIRE);
        put("HemoshroomBlock", MapColor.NETHER);
        put("HemototemBlock", MapColor.FIRE);
        put("DrenchedFenceBlock", MapColor.FIRE);
        put("DrenchedDoorBlock", MapColor.FIRE);
        put("DrenchedGateBlock", MapColor.FIRE);
        put("DriedBookshelfBlock", MapColor.FIRE);
        put("GloomdoomBlock", MapColor.TERRACOTTA_YELLOW);
        put("GorestoolBlock", MapColor.FIRE);
        put("FernFlowerBlock", MapColor.TERRACOTTA_ORANGE);
        put("MassGrassBlock", MapColor.NETHER);
        put("RedshroomBlock", MapColor.NETHER);
        put("BloodfungusBlock", MapColor.NETHER);
        put("BigBloodfungusBlock", MapColor.NETHER);
        put("FernBlock", MapColor.TERRACOTTA_ORANGE);
        put("DoombloomBlock", MapColor.TERRACOTTA_YELLOW);
        put("CrimsonshroomBlock", MapColor.CRIMSON_STEM);
        put("BoneshroomBlock", MapColor.TERRACOTTA_ORANGE);
        put("GumbloomBlock", MapColor.TERRACOTTA_PINK);
        put("GumpopBlock", MapColor.TERRACOTTA_PINK);
        put("BloodcapBlock", MapColor.NETHER);
        put("TeethcarrotBlock", MapColor.QUARTZ);
        put("MarrowfungusBlock", MapColor.FIRE);
        put("FlatcapbigBlock", MapColor.TERRACOTTA_ORANGE);
        put("FlatcapBlock", MapColor.TERRACOTTA_ORANGE);
        put("FlatcapsmallBlock", MapColor.TERRACOTTA_ORANGE);
        put("TeethBlock", MapColor.QUARTZ);
        put("RattailsBlock", MapColor.TERRACOTTA_ORANGE);
        put("DecayOutburstBlock", MapColor.CRIMSON_HYPHAE);
        put("Do2Block", MapColor.CRIMSON_HYPHAE);
        put("Do3Block", MapColor.CRIMSON_HYPHAE);
        put("Do4Block", MapColor.TERRACOTTA_ORANGE);
        put("Do5Block", MapColor.CRIMSON_HYPHAE);
        put("Do6Block", MapColor.TERRACOTTA_ORANGE);
        put("Do7Block", MapColor.TERRACOTTA_ORANGE);
        put("Do8Block", MapColor.CRIMSON_HYPHAE);
        put("Do9Block", MapColor.CRIMSON_HYPHAE);
        put("SoakedLeavesBlock", MapColor.COLOR_ORANGE);
        put("DecayingLeavesBlock", MapColor.COLOR_ORANGE);
        put("SpineBlock", MapColor.QUARTZ);
        put("SpineBrainBlock", MapColor.WARPED_HYPHAE);
        put("MortemGrowthBlock", MapColor.CRIMSON_STEM);
        put("MortemSinewBlock", MapColor.CRIMSON_STEM);
        put("MortemTailsBlock", MapColor.CRIMSON_STEM);
        put("DoubleBloodGrassBlock", MapColor.TERRACOTTA_ORANGE);
        put("MeatSlabBlock", MapColor.TERRACOTTA_PINK);
        put("MeatStairsBlock", MapColor.TERRACOTTA_PINK);
        put("DriedGrassBlock", MapColor.SAND);
        put("DriedGrassletsBlock", MapColor.SAND);
        put("DryBushBlock", MapColor.SAND);
        put("TallDriedGrassBlock", MapColor.SAND);
        put("SmallDriedGrassBlock", MapColor.SAND);
        put("SmallHornBlock", MapColor.FIRE);
        put("BloodroseBlock", MapColor.FIRE);
        put("TallBloodroseBlock", MapColor.FIRE);
        put("DriedLeavesBlock", MapColor.COLOR_GREEN);

//        put("BigleafBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("BigveinBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("CarvingCancerBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DamagedBonesBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DamagedMusclesBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DecomposingBricks2Block", MapColor.COLOR_LIGHT_GREEN);
//        put("DecomposingBricks3Block", MapColor.COLOR_LIGHT_GREEN);
//        put("DecomposingBricks4Block", MapColor.COLOR_LIGHT_GREEN);
//        put("DecomposingBricks5Block", MapColor.COLOR_LIGHT_GREEN);
//        put("DecomposingBricksBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedCabinetBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedChairBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedDoorBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedDrawerBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedFenceBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedFenceGateBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedPressurePlateBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedSofaBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedTableBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DriedTrapdoorBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DunEyeBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DunEyesBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DunLootBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DunoreBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("DunVeinBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("ES2Block", MapColor.COLOR_LIGHT_GREEN);
//        put("ES3Block", MapColor.COLOR_LIGHT_GREEN);
//        put("ES4Block", MapColor.COLOR_LIGHT_GREEN);
//        put("ES5Block", MapColor.COLOR_LIGHT_GREEN);
//        put("EvaporatingVoidturfBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("ExpandedStoneBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("FerumBarBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("FleshdoorBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("FleshdoorOpenBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("FurCarpetBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("GloombloomBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("GreylogBookshelfBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("GreylogCabinetBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("GreylogChairBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("GreylogDrawerBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("GreylogSofaBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("GreylogTableBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("GrinningFurnaceBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("LeafVeinsBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("LeafVeinsendBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("MoldHairsBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("MoldSproutBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("MoltenCrystalBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("MoltenFlowerBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("MoltenGrassBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("MoltenLeafletBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("MoltenSpikesBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("MoltenStoneBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("Rockslab2Block", MapColor.COLOR_LIGHT_GREEN);
//        put("Rockslab3Block", MapColor.COLOR_LIGHT_GREEN);
//        put("RockslabBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SmallMoltenFlowerBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SoakedFenceBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SoakedGateBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SoakedPressurePlateBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SoakedTrapdoorBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SoakedVinesBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SoakedWindowBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SpineFenceBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SpineFenceCornerBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SpineGateBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("SpineGateOpenBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("TeethingDoorBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("TeethingFenceBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("TeethingFenceGateBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("TeethingTrapdoorBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("TenderMeatWallBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("TendrilsBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("TendrilsNoanimBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("TentacleCancerBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("TentacleSpawnBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("ToothyChestBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("VeinyTumorBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("ViloreBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("VoidturfBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedBookshelfBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedBushBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedCabinetBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedChairBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedDoorBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedDrawerBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedFenceBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedFenceGateBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedFungusBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedLeavesBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedPressurePlateBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedSofaBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedStrainsBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedTableBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WastedTrapdoorBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WasteGrassBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WoodTeethBlock", MapColor.COLOR_LIGHT_GREEN);
//        put("WoodToothBlock", MapColor.COLOR_LIGHT_GREEN);
    }};

    public SonsOfMacabre(FMLJavaModLoadingContext context) {
        IEventBus modEventBus = context.getModEventBus();

        modEventBus.addListener(this::commonSetup);

        context.registerConfig(ModConfig.Type.COMMON, Config.SPEC);
    }

    private void commonSetup(final FMLCommonSetupEvent event) {

        // Register custom portal if enabled
        if (Config.enableCustomPortal)
            CustomPortalBuilder.beginPortal()
                    .frameBlock(SonsOfSinsModBlocks.FLESH_BLOCK.get())
                    .lightWithItem(MacabreModItems.CRYSTALIZED_BLOOD.get())
                    .destDimID(ResourceLocation.fromNamespaceAndPath("macabre", "the_pit"))
                    .tintColor(227, 0, 0)
                    .registerPortal();

        CraftingHelper.register(new ConfigCondition.Serializer());
    }
}
